import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { EventEmitter } from 'events';

vi.mock('child_process', () => ({ spawn: vi.fn() }));
vi.mock('fs/promises', () => ({
  readFile: vi.fn(),
  unlink: vi.fn().mockResolvedValue(undefined),
}));

import { spawn } from 'child_process';
import * as fs from 'fs/promises';
import { PrusaSlicerService } from '../../src/services/prusa-slicer.service';

const mockSpawn   = vi.mocked(spawn);
const mockRead    = vi.mocked(fs.readFile);
const mockUnlink  = vi.mocked(fs.unlink);

const GCODE_OK = `
; generated by PrusaSlicer
; filament used [mm] = 4567.89
; filament used [g] = 12.45
; filament cost = 0.50
`;

const GCODE_NO_WEIGHT = `
; generated by PrusaSlicer
; some other line
`;

function makeProc() {
  const proc = new EventEmitter() as ReturnType<typeof spawn>;
  (proc as any).kill = vi.fn();
  (proc as any).stdin = null;
  (proc as any).stdout = new EventEmitter();
  (proc as any).stderr = new EventEmitter();
  return proc;
}

describe('PrusaSlicerService', () => {
  let svc: PrusaSlicerService;

  beforeEach(() => {
    vi.clearAllMocks();
    mockUnlink.mockResolvedValue(undefined);
    svc = new PrusaSlicerService('prusa-slicer', '0.20');
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('caso éxito: devuelve gramosTotal parseado del gcode', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);
    mockRead.mockResolvedValue(GCODE_OK as any);

    setImmediate(() => proc.emit('close', 0));

    const result = await svc.slice('/tmp/abc123.stl', 1.24);

    expect(result.gramosTotal).toBe(12.45);
    expect(mockUnlink).toHaveBeenCalledWith('/tmp/abc123.gcode');
  });

  it('caso éxito: llama al binario con los flags correctos', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);
    mockRead.mockResolvedValue(GCODE_OK as any);

    setImmediate(() => proc.emit('close', 0));
    await svc.slice('/tmp/abc123.stl', 1.24);

    expect(mockSpawn).toHaveBeenCalledWith(
      'prusa-slicer',
      expect.arrayContaining([
        '--fill-density', '10%',
        '--perimeters', '2',
        '--nozzle-diameter', '0.40',
        '--layer-height', '0.20',
        '--filament-density', '1.24',
        '--export-gcode',
        '--output', '/tmp/abc123.gcode',
        '/tmp/abc123.stl',
      ]),
      expect.any(Object),
    );
  });

  it('EC-001: lanza cuando el binario no existe (ENOENT)', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);

    setImmediate(() => proc.emit('error', Object.assign(new Error('spawn error'), { code: 'ENOENT' })));

    await expect(svc.slice('/tmp/abc123.stl', 1.24)).rejects.toThrow();
  });

  it('EC-002: lanza cuando PrusaSlicer sale con exit code distinto de 0', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);

    setImmediate(() => proc.emit('close', 1));

    await expect(svc.slice('/tmp/abc123.stl', 1.24)).rejects.toThrow('exit code 1');
  });

  it('EC-003: lanza y mata el proceso cuando supera el timeout configurado', async () => {
    vi.useFakeTimers();

    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);

    const shortTimeoutSvc = new PrusaSlicerService('prusa-slicer', '0.20', 500);
    const slicePromise = shortTimeoutSvc.slice('/tmp/abc123.stl', 1.24);
    // Adjuntar el handler de rechazo ANTES de avanzar timers para evitar unhandledRejection
    const assertion = expect(slicePromise).rejects.toThrow('timeout');

    await vi.advanceTimersByTimeAsync(501);
    await assertion;

    expect((proc as any).kill).toHaveBeenCalledWith('SIGKILL');
  });

  it('EC-004: lanza cuando el gcode no contiene la línea filament used [g]', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);
    mockRead.mockResolvedValue(GCODE_NO_WEIGHT as any);

    setImmediate(() => proc.emit('close', 0));

    await expect(svc.slice('/tmp/abc123.stl', 1.24)).rejects.toThrow('parse failed');
  });

  it('EC-005: lanza cuando el valor parseado es 0', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);
    mockRead.mockResolvedValue('; filament used [g] = 0' as any);

    setImmediate(() => proc.emit('close', 0));

    await expect(svc.slice('/tmp/abc123.stl', 1.24)).rejects.toThrow('invalid value');
  });

  it('limpieza: elimina el gcode incluso cuando el parse falla', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);
    mockRead.mockResolvedValue(GCODE_NO_WEIGHT as any);

    setImmediate(() => proc.emit('close', 0));

    await expect(svc.slice('/tmp/abc123.stl', 1.24)).rejects.toThrow();
    expect(mockUnlink).toHaveBeenCalledWith('/tmp/abc123.gcode');
  });

  it('progreso: parsea líneas "N => etapa" del stdout y llama a onProgress', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);
    mockRead.mockResolvedValue(GCODE_OK as any);
    const onProgress = vi.fn();

    setImmediate(() => {
      (proc.stdout as EventEmitter).emit('data', Buffer.from('10 => Processing triangulated mesh\n'));
      (proc.stdout as EventEmitter).emit('data', Buffer.from('45 => Making infill\n'));
      proc.emit('close', 0);
    });

    await svc.slice('/tmp/abc123.stl', 1.24, undefined, onProgress);

    expect(onProgress).toHaveBeenNthCalledWith(1, 10, 'Processing triangulated mesh');
    expect(onProgress).toHaveBeenNthCalledWith(2, 45, 'Making infill');
  });

  it('progreso: reconstruye una línea partida en varios chunks del stream', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);
    mockRead.mockResolvedValue(GCODE_OK as any);
    const onProgress = vi.fn();

    setImmediate(() => {
      (proc.stdout as EventEmitter).emit('data', Buffer.from('65 => Searching '));
      (proc.stdout as EventEmitter).emit('data', Buffer.from('support spots\n'));
      proc.emit('close', 0);
    });

    await svc.slice('/tmp/abc123.stl', 1.24, undefined, onProgress);

    expect(onProgress).toHaveBeenCalledWith(65, 'Searching support spots');
  });

  it('progreso: ignora líneas de stdout que no matchean el formato "N => etapa"', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);
    mockRead.mockResolvedValue(GCODE_OK as any);
    const onProgress = vi.fn();

    setImmediate(() => {
      (proc.stdout as EventEmitter).emit('data', Buffer.from('some unrelated log line\n'));
      proc.emit('close', 0);
    });

    await svc.slice('/tmp/abc123.stl', 1.24, undefined, onProgress);

    expect(onProgress).not.toHaveBeenCalled();
  });

  it('EC-002b: el error de exit code distinto de 0 incluye el tail de stderr para diagnóstico', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);

    setImmediate(() => {
      (proc.stderr as EventEmitter).emit('data', Buffer.from('error: Unable to repair mesh\n'));
      proc.emit('close', 1);
    });

    await expect(svc.slice('/tmp/abc123.stl', 1.24)).rejects.toThrow('error: Unable to repair mesh');
  });

  it('progreso: onProgress es opcional, no rompe el flujo si se omite', async () => {
    const proc = makeProc();
    mockSpawn.mockReturnValue(proc as any);
    mockRead.mockResolvedValue(GCODE_OK as any);

    setImmediate(() => {
      (proc.stdout as EventEmitter).emit('data', Buffer.from('10 => Processing triangulated mesh\n'));
      proc.emit('close', 0);
    });

    await expect(svc.slice('/tmp/abc123.stl', 1.24)).resolves.toMatchObject({ gramosTotal: 12.45 });
  });
});
